# Generated by Django 3.1.2 on 2021-11-26 07:06

import adminsite.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(max_length=255)),
                ('Campaign_Sate', models.IntegerField()),
                ('Campaign_Starttime', models.DateTimeField(default=adminsite.models.today_start)),
                ('Campaign_Endtime', models.DateTimeField(default=adminsite.models.tomorrow)),
                ('Create_At', models.DateTimeField(auto_now_add=True)),
                ('Modified_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('campaing_name', models.CharField(max_length=255)),
                ('campaign_content', models.CharField(max_length=255)),
                ('content_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_receiver', models.CharField(max_length=255, null=True)),
                ('user_send', models.CharField(default='crontab', max_length=100)),
                ('time_send', models.DateTimeField(default=adminsite.models.today_start)),
                ('msg_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'campaign_history',
            },
        ),
        migrations.CreateModel(
            name='UserCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('thread_id', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'campaign_user',
            },
        ),
        migrations.CreateModel(
            name='User_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_room',
            },
        ),
        migrations.CreateModel(
            name='User_Group_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('Users', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_group_mapping',
            },
        ),
        migrations.CreateModel(
            name='User_Campaign_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_id', models.CharField(max_length=255)),
                ('Campaigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.campaign')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_Campaign_mapping',
            },
        ),
        migrations.CreateModel(
            name='User_Behavious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('Campaign_User_Behavious', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behavious',
            },
        ),
        migrations.CreateModel(
            name='List_Content_Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(max_length=255)),
                ('Campaign_Content', models.CharField(max_length=255)),
                ('Create_At', models.DateTimeField(auto_now_add=True)),
                ('Modified_At', models.DateTimeField(auto_now=True)),
                ('Create_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Create_By_Usercontent', to=settings.AUTH_USER_MODEL)),
                ('Modified_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Modified_By_User_Content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_conten_campaign',
            },
        ),
        migrations.CreateModel(
            name='GroupCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='user_group_campaign_mapping', to='adminsite.UserCampaign')),
            ],
            options={
                'db_table': 'campaign_group',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='Campaign_Content',
            field=models.ManyToManyField(related_name='List_Content_Campaign', to='adminsite.List_Content_Campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Campaign_Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.groupcampaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Create_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Create_By_User_Campaign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Modified_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Modified_By_User_Campaign', to=settings.AUTH_USER_MODEL),
        ),
    ]
