# Generated by Django 3.1.2 on 2021-11-26 11:37

import adminsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignhistory',
            name='time_reply',
            field=models.DateTimeField(default=adminsite.models.today_start, null=True),
        ),
    ]
