# Generated by Django 3.1.2 on 2021-11-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_campaignhistory_time_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignhistory',
            name='time_reply',
            field=models.DateTimeField(null=True),
        ),
    ]
